# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: flashcards_development
  host: localhost
  pool: 5
  timeout: 5000
  username: db_owner
  password: qwerty

test:
  adapter: postgresql
  encoding: unicode
  database: flashcards_test
  host: localhost
  pool: 5
  timeout: 5000
  username: db_owner
  password: qwerty

production:
  <<: *default
  database: db/production.sqlite3

